export const NAV_LINKS = ["Home", "About", "Services", "Courses", "Stats", "Contact"];

export const SERVICES = [
  { icon: "💻", title: "Custom Software Development", desc: "Enterprise-grade custom software tailored to your complex business workflows. From ERP systems to backend APIs, we build scalable solutions for modern enterprises." },
  { icon: "🔍", title: "SEO Services", desc: "Dominate search rankings and drive sustainable organic traffic. We combine technical audits with keyword intelligence to build your brand's digital authority." },
  { icon: "🎨", title: "UI/UX Design", desc: "User-focused design that blends creativity with usability. We create intuitive interfaces that increase engagement and drive higher conversions." },
  { icon: "📣", title: "Digital Marketing", desc: "Results-driven marketing strategies designed to increase brand visibility, generate leads, and maximize ROI across multiple digital channels." },
  { icon: "📱", title: "Social Media Marketing", desc: "Build a loyal community and drive engagement across all major social platforms. We turn likes into loyalty through strategic content and community management." },
  { icon: "🌐", title: "Web Development", desc: "Enterprise-grade custom web applications tailored to your business needs. We build scalable, secure, and high-performance solutions that drive digital transformation." },
  { icon: "⚡", title: "WordPress Development", desc: "Results-driven marketing strategies designed to increase brand visibility, generate leads, and maximize ROI across multiple digital channels." },
  { icon: "📊", title: "Data Analysis Services", desc: "Turn raw data into actionable insights. Our analytics solutions help you optimize operations, improve performance, and identify new growth opportunities." },
];

export const COURSES = [
  {
    icon: "MERN",
    title: "MERN Full Stack Development",
    badge: "POPULAR",
    color: "from-green-500 to-emerald-700",
    duration: "6 Months",
    level: "Beginner → Pro",
    topics: ["MongoDB & Express", "React & Next.js", "Node.js & APIs", "State Management", "Cloud Deployment"],
    cert: true,
    jobs: ["MERN Stack Developer", "Full Stack Engineer", "Frontend Architect"],
  },
  {
    icon: "AI",
    title: "Full Stack AI (ML + DL)",
    badge: "ADVANCED",
    color: "from-emerald-400 to-green-600",
    duration: "6 Months",
    level: "Intermediate → Expert",
    topics: ["Python for AI", "Machine Learning", "Deep Learning", "Neural Networks", "AI Model Deployment"],
    cert: true,
    jobs: ["AI Engineer", "ML Specialist", "Data Scientist"],
  },
  {
    icon: "SEC",
    title: "Cybersecurity & Ethical Hacking",
    badge: "ELITE",
    color: "from-green-600 to-teal-700",
    duration: "6 Months",
    level: "Beginner → Advanced",
    topics: ["Ethical Hacking", "Network Security", "Vulnerability Assessment", "Penetration Testing", "Digital Forensics"],
    cert: true,
    jobs: ["Security Researcher", "Ethical Hacker", "Security Consultant"],
  },
  {
    icon: "DATA",
    title: "Data Analysis Professional",
    badge: "IN-DEMAND",
    color: "from-emerald-500 to-teal-600",
    duration: "4 Months",
    level: "Beginner → Pro",
    topics: ["Advanced Excel", "SQL Databases", "Power BI / Tableau", "Python for Data", "Statistical Modeling"],
    cert: true,
    jobs: ["Data Analyst", "BI Specialist", "Business Analyst"],
  },
  {
    icon: "ENG",
    title: "Spoken English Mastery",
    badge: "ESSENTIAL",
    color: "from-green-400 to-emerald-500",
    duration: "3 Months",
    level: "All Levels",
    topics: ["Fluency & Accent", "Business Communication", "Public Speaking", "Vocabulary Building", "IELTS Preparation"],
    cert: true,
    jobs: ["Corporate Trainer", "Client Manager", "Public Speaker"],
  },
  {
    icon: "UX",
    title: "UI / UX Design",
    badge: "CREATIVE",
    color: "from-teal-400 to-green-500",
    duration: "4 Months",
    level: "Beginner → Pro",
    topics: ["Figma Mastery", "User Research", "Wireframing", "Prototyping", "Visual Design Principles"],
    cert: true,
    jobs: ["Product Designer", "UI/UX Designer", "UX Researcher"],
  },
  {
    icon: "OPS",
    title: "DevOps Engineering",
    badge: "TECHNICAL",
    color: "from-emerald-600 to-green-800",
    duration: "5 Months",
    level: "Intermediate → Pro",
    topics: ["Docker & Kubernetes", "CI/CD Pipelines", "AWS / Azure", "Infrastructure as Code", "Monitoring Tools"],
    cert: true,
    jobs: ["DevOps Engineer", "Cloud Architect", "SRE Engineer"],
  },
  {
    icon: "SOC",
    title: "SOC Analyst",
    badge: "FOCUSED",
    color: "from-green-700 to-emerald-900",
    duration: "4 Months",
    level: "Intermediate",
    topics: ["SIEM Tools", "Incident Response", "Threat Hunting", "Security Monitoring", "Compliance Frameworks"],
    cert: true,
    jobs: ["SOC Analyst L1/L2", "Incident Responder", "Security Engineer"],
  },
  {
    icon: "MKT",
    title: "Digital Marketing with AI",
    badge: "MODERN",
    color: "from-emerald-400 to-teal-500",
    duration: "3 Months",
    level: "Beginner → Pro",
    topics: ["AI for Content", "Social Media Ads", "Email Automation", "Analytics & ROI", "Growth Hacking"],
    cert: true,
    jobs: ["Growth Marketer", "AI Content Strategist", "Ads Manager"],
  },
  {
    icon: "DSN",
    title: "Graphic Designing",
    badge: "ARTISTIC",
    color: "from-green-500 to-teal-400",
    duration: "4 Months",
    level: "Beginner → Pro",
    topics: ["Photoshop & Illustrator", "Brand Identity", "Typography", "Ad Creative Design", "Portfolio Building"],
    cert: true,
    jobs: ["Brand Designer", "Visual Artist", "Creative Director"],
  },
  {
    icon: "SEO",
    title: "SEO (Search Engine Optimization)",
    badge: "RANKING",
    color: "from-teal-600 to-emerald-700",
    duration: "3 Months",
    level: "Beginner → Intermediate",
    topics: ["Technical SEO", "Keyword Research", "On-Page / Off-Page", "Backlink Strategy", "Local SEO"],
    cert: true,
    jobs: ["SEO Specialist", "Search Strategist", "Content Optimizer"],
  },
];

export const STATS = [
  { value: "100+", num: 100, suffix: "+", label: "Students Mentored", sub: "and growing every cohort", icon: "🎓" },
  { value: "50+", num: 50, suffix: "+", label: "Projects Delivered", sub: "for clients across industries", icon: "🚀" },
  { value: "98%", num: 98, suffix: "%", label: "Satisfaction Rate", sub: "rated excellent or outstanding", icon: "⭐" },
  { value: "11", num: 11, suffix: "", label: "Expert Courses", sub: "with more launching soon", icon: "📚" },
];

export const TESTIMONIALS = [
  { name: "Ali Hassan", role: "Cybersecurity Graduate", text: "Zynex transformed my career. The cybersecurity course was hands-on, industry-relevant, and the job support was incredible.", avatar: "AH" },
  { name: "Sara Khan", role: "Web Developer", text: "I landed my first remote job within 2 months of completing the Web Dev course. The curriculum is world-class.", avatar: "SK" },
  { name: "Umar Farooq", role: "Data Analyst", text: "The data analytics program gave me skills that immediately translated into a 40% salary increase at my current job.", avatar: "UF" },
];

export const WHY_ZYNEX = [
  { icon: "🏅", title: "Certificate on Completion", desc: "Every course ends with a globally recognized certificate you can proudly display on LinkedIn and your resume." },
  { icon: "💼", title: "Job Placement Support", desc: "Our career team connects graduates directly with hiring partners. We don't stop until you're placed." },
  { icon: "👥", title: "Community Access", desc: "Join a thriving community of 100+ alumni, get peer support, and access lifetime updates to course material." },
  { icon: "🧑‍🏫", title: "Industry Expert Mentors", desc: "Learn from professionals actively working in cybersecurity, development, and data — not just theorists." },
  { icon: "🔬", title: "Hands-On Projects", desc: "Build a real portfolio with capstone projects, CTF challenges, and live client work during your course." },
  { icon: "📅", title: "Flexible Scheduling", desc: "Morning, evening, and weekend batches to fit your lifestyle. Learn at your pace without sacrificing quality." },
];
